### ISSUE TITLE
Hardcoded block&item name?!

### ISSUE THREAD

**Issue by 3TUSK** [panda2134/CompactLavaGenerator#4]
Apparently I realize that you have no `*.lang` file! Please localize those items & blocks name!
（简单来说就是不支持本地化不爽）

**Comment by panda2134** [comment]
我才加了中文翻译。。。你看看233

**Comment by 3TUSK** [comment]
找了半天没找到系列...

**Comment by 3TUSK** [comment]
Get. 43f2b36961e5be37875c6b2e2fc179d266b2a413
