### ISSUE TITLE
mcmod.info file cannot be parsed as valid JSON

### ISSUE THREAD

**Issue by bookerthegeek** [panda2134/CompactLavaGenerator#6]
https://gist.github.com/bookerthegeek/5a6f85906a5c663b2b0d

Just an F.Y.I.

**Comment by panda2134** [comment]
#5

**Comment by panda2134** [comment]
this bug had been reported and fixed.

**Comment by bookerthegeek** [comment]
Sorry, did not see that. Forgot to check on the closed issues.
